# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Attend
    identifier: attend
    weight: 10
  - name: Registration
    parent: attend
    url: registration
    weight: 11
  - name: Call for Abstracts
    parent: attend
    url: abstract
    weight: 13
  - name: Volunteer at MWGLRM
    parent: attend
    url: volunteer
    weight: 15
  - name: Program
    url: program
    weight: 20
  - name: Exposition
    url: exposition
    weight: 50
  - name: Awards
    identifier: award1
    weight: 60
  - name: Awards & Criteria
    parent: award1
    url: awards
    weight: 61
  - name: Award Winners
    parent: award1
    url: awardwin
    weight: 63
  - name: Lodging & Attractions
    url: lodgingtravel
    weight: 80
  - name: Contact
    identifier: contact1
    weight: 90
  - name: Contact Info
    parent: contact1
    url: contact
    weight: 91
  - name: Organizing Committee
    parent: contact1
    url: people
    weight: 93
